// FILE NÀY CHỈ DÙNG ĐỂ CHỨA DỮ LIỆU VÀ LINK
// Ní điền link vào giữa 2 dấu nháy "" ở dòng 'link' nhé.

const OFFERS = [
    // --- 1. VAY TIỀN ONLINE ---
    { id: "moneycatvn", type: "vay", name: "MoneyCat", link: "", logo: "https://moneycat.vn/public/img/logo.png", desc: "0% lãi suất lần đầu, duyệt 5 phút" },
    { id: "moneyveo", type: "vay", name: "MoneyVeo", link: "", logo: "https://moneyveo.vn/img/logo.svg", desc: "Hỗ trợ tư vấn tài chính 24/7" },
    { id: "tima", type: "vay", name: "Tima", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/tima.png", desc: "Vay qua đăng ký xe máy/oto" },
    { id: "f88", type: "vay", name: "F88", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/f88.png", desc: "Cầm cố tài sản, 15 phút có tiền" },
    { id: "jeffapp", type: "vay", name: "Jeff App", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/jeffapp.jpg", desc: "Sàn so sánh vay, duyệt nhiều nguồn" },
    { id: "vayvnd", type: "vay", name: "VayVND", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo-vayvnd.png", desc: "Vay cấp tốc online" },
    { id: "dong247", type: "vay", name: "Dong247", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/dong247.png", desc: "Duyệt vay tự động bằng AI" },
    { id: "crezu", type: "vay", name: "Crezu", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/crezu.png", desc: "0% lãi suất cho khoản vay đầu" },
    { id: "kamo", type: "vay", name: "Kamo", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/kamo.jpg", desc: "Thủ tục đơn giản, nhận tiền ngay" },
    { id: "kavay", type: "vay", name: "Kavay", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/Kavay.png", desc: "Giải ngân siêu tốc 24/7" },
    { id: "bimo", type: "vay", name: "Bimo", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/bimo.jpg", desc: "Vay tiền mặt online" },
    { id: "cashspace", type: "vay", name: "Cashspace", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/vn.png", desc: "Tìm khoản vay tốt nhất" },
    { id: "vaymini", type: "vay", name: "VayMini", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/IMG_5578.JPG", desc: "Khoản vay nhỏ, giải ngân nhanh" },
    { id: "tieno", type: "vay", name: "Tieno", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/tieno-1.jpg", desc: "Duyệt hồ sơ cực dễ" },
    { id: "skycredit", type: "vay", name: "Sky Credit", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/photo_2025-05-07_11-18-14.jpg", desc: "Vay tín chấp lãi suất thấp" },
    { id: "vaymeo", type: "vay", name: "Vaymeo", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Vaymeo.png", desc: "Vay online mọi lúc mọi nơi" },
    { id: "binvay", type: "vay", name: "BinVay", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo-binvay.jpeg", desc: "Tiền về tài khoản trong ngày" },
    { id: "agovay", type: "vay", name: "Agovay", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/49c27e1001bcd3e28aad.jpg", desc: "Vay tiền online chuyển khoản" },
    { id: "bfcmoney", type: "vay", name: "BFC Money", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo-BFC.png", desc: "Vay tiền qua iCloud" },
    { id: "fago", type: "vay", name: "Fago", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/fago_icon.png", desc: "Vay tiền nhanh Fago" },
    { id: "navacash", type: "vay", name: "Navacash", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/nava_icon.jpeg", desc: "Lãi suất ưu đãi hấp dẫn" },
    { id: "creditvn", type: "vay", name: "Credit.vn", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/Group%20198.png", desc: "Cổng thông tin tài chính uy tín" },
    { id: "credy", type: "vay", name: "Credy", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/credy.png", desc: "Giải pháp tài chính linh hoạt" },
    { id: "vimayman", type: "vay", name: "Ví May Mắn", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Ví may mắn.png", desc: "Ví vay tiền tiện lợi" },
    { id: "shbfinance", type: "vay", name: "SHB Finance", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/SHBF logo.webp", desc: "Vay tiền mặt SHB Finance" },
    { id: "cayvang", type: "vay", name: "CayVang", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/1667-cayvang-vn-2024-05-15.png", desc: "Vay Cây Vàng - Duyệt nhanh" },
    { id: "vietmoney", type: "vay", name: "VietMoney", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/vietmoney.png", desc: "Cầm đồ trực tuyến an toàn" },
    { id: "binixo", type: "vay", name: "Binixo", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo%20binixo%20%281%29.png", desc: "Kết nối vay nhanh" },
    { id: "fec", type: "vay", name: "FE CREDIT", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Logo_FullColor.png", desc: "Vay tiêu dùng tín chấp" },
    { id: "finzone", type: "vay", name: "Finzone", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/finzone-1.png", desc: "Sàn tài chính kết nối khoản vay" },
    { id: "redbag-2", type: "vay", name: "Redbag", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/RedBag-LOGO-Standard-Horizontal.png", desc: "Túi thần tài chính" },
    { id: "cashingpro", type: "vay", name: "Cashing Pro", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/LOGO-05.png", desc: "Giải pháp cầm cố tài sản" },
    { id: "dongshopsun1", type: "vay", name: "Đồng Shop Sun", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo.jpeg", desc: "Vay tiền Nhật Bản" },
    { id: "avay", type: "vay", name: "Avay", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo-avay.png", desc: "Vay tín chấp Avay" },

    // --- 2. NGÂN HÀNG SỐ ---
    { id: "kbankpayroll", type: "bank", name: "KBank", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo.png", desc: "Mở TK nhận thưởng hấp dẫn" },
    { id: "mb-ios", type: "bank", name: "MB Bank", link: "", logo: "https://upload.wikimedia.org/wikipedia/commons/2/25/Logo_MB_new.png", desc: "Tài khoản số đẹp miễn phí" },
    { id: "cake", type: "bank", name: "Cake Bank", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/cake.png", desc: "Ngân hàng số Cake by VPBank" },
    { id: "tnex-cashloan", type: "bank", name: "TNEX", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/tnex_finnace_logo_65a9f6aa9fee9.png", desc: "Ngân hàng thuần số miễn phí" },
    { id: "msb-ekyc", type: "bank", name: "MSB mBank", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo-msb.png", desc: "Mở tài khoản MSB số đẹp" },
    { id: "vpbankneo", type: "bank", name: "VPBank NEO", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/VPBank.png", desc: "Ngân hàng số toàn năng" },
    { id: "acb1", type: "bank", name: "ACB One", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/ACB.png", desc: "Ngân hàng số ACB One" },
    { id: "ocbcode1", type: "bank", name: "OCB OMNI", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Picture1.png", desc: "Ngân hàng số OCB OMNI" },
    { id: "vikki", type: "bank", name: "Vikki", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Vikki_Original Logo Vikki DigitaL_Online.png", desc: "Ngân hàng số Vikki" },
    { id: "uob-ekyc", type: "bank", name: "UOB", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/uob-logo-472x226.png", desc: "Tài khoản thanh toán UOB" },
    { id: "lpbank", type: "bank", name: "LPBank", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/666c22c1e8fc6ab7134d3f1b_lpbank_logo.jpg", desc: "Tài khoản LPBank" },
    { id: "msb-tktt", type: "bank", name: "MSB TKTT", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo-msb-inkythuatso-07-13-40-57.jpg", desc: "Tài khoản thanh toán MSB" },

    // --- 3. THẺ TÍN DỤNG ---
    { id: "vib-2", type: "the", name: "VIB Credit", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/vib-2.png", desc: "Mở thẻ online, miễn phí thường niên" },
    { id: "tpbankevo", type: "the", name: "TPBank EVO", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/Asset%204.png", desc: "Thẻ Evo 100% Online" },
    { id: "cake-cc", type: "the", name: "Be Visa", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/Logo%201%20copy.jpg", desc: "Thẻ Cake x Be - Hoàn tiền" },
    { id: "vib-3", type: "the", name: "VIB Zalo", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/Asset%202.png", desc: "Mở thẻ VIB qua Zalo" },
    { id: "vpbank-mc", type: "the", name: "VPBank Auto", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/CC-01.png", desc: "Thẻ VPBank duyệt tự động" },
    { id: "finmart", type: "the", name: "Finmart", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/logo finmart.png", desc: "Thẻ tín dụng Finmart" },
    { id: "cake-web", type: "the", name: "Cake Thẻ", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Cake copy2 .jpg", desc: "Thẻ Cake Freedom" },
    { id: "vib-card", type: "the", name: "VIB MAX", link: "", logo: "https://storage.googleapis.com/hyperlead-public/production/assets/offers/vib-2.png", desc: "Thẻ tín dụng VIB Max" }
];
